# Generated by Django 4.1.5 on 2023-01-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='contact',
            field=models.ManyToManyField(to='rb.contact'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(to='rb.education'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.ManyToManyField(to='rb.languages'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.ManyToManyField(help_text='link to the projects of the user', to='rb.project'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='workx',
            field=models.ManyToManyField(to='rb.workx'),
        ),
    ]
