# Generated by Django 4.1.5 on 2023-01-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0005_alter_education_e_yr_alter_workx_e_yr'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.CharField(default='sdfvs.com', max_length=522),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.CharField(default='ersdfrs.com', max_length=522),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.CharField(default='cedsfn.com', max_length=522),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='ph',
            field=models.CharField(default='2342354', max_length=522),
            preserve_default=False,
        ),
    ]
