# Generated by Django 4.1.5 on 2023-01-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0006_resume_email_resume_github_resume_linkedin_resume_ph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='contact',
        ),
    ]
